apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Release.Name }}-keyvault
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  secretObjects:
    - secretName: {{ .Release.Name }}-secrets
      type: Opaque
      data:
        - objectName: mediflow-api-key
          key: API_KEY
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "2ca107ed-4d58-42a7-a3b2-92310920aa95"
    keyvaultName: "kv-mediflow-dev"
    tenantId: "284fcab9-b353-44fb-8507-c7a3b277c19e"
    objects: |
      array:
        - |
          objectName: mediflow-api-key
          objectType: secret
